# code: language=ansible
- name: Deploy datasette
  hosts: grape_surgery
  become: true

  roles:
    - server

  vars_files:
    - ../configs/vars.yml

  tasks:
    - name: Install datasette
      ansible.builtin.pip:
        state: present
        name: datasette

    - name: Template datasette.service
      ansible.builtin.template:
        src: ../configs/datasette.service.j2
        dest: "{{ systemd_unit_dir }}/datasette.service"
        mode: ugo=r
      notify:
        - Reload systemd
        - Reload datasette

    - name: Template datasette-watch
      ansible.builtin.template:
        src: ../configs/datasette-watch.{{ item }}.j2
        dest: "{{ systemd_unit_dir }}/datasette-watch.{{ item }}"
        mode: ugo=r
      with_items:
        - service
        - path
      notify:
        - Reload systemd
        - Reload datasette-watch

  handlers:

    - name: Reload datasette
      ansible.builtin.service:
        name: datasette
        state: restarted
        enabled: true

    - name: Reload datasette-watch
      ansible.builtin.service:
        name: datasette-watch.{{ item }}
        state: restarted
        enabled: true
      with_items:
        - service
        - path
