# vim: et ts=4 sw=4 ft=toml

[[job]]
every = '5 minutes'
cmd = ['bash', '{{ file("spotti-downbot-cron") }}']

[[job]]
every = '6 hours'
cmd = ['curl', '-X', 'POST', 'grape.surgery/size/clean']

[[job]]
every = '6 hours'
cmd = [
    'supervisorctl',
    '-c',
    '{{ file("supervisord-config") }}',
    'restart',
    'dop',
]

#[[job]]
#every = '2 weeks'
#with-env = {
#    AWS_ACCESS_KEY_ID = '{{ SECRET["aws-id"] }}',
#    AWS_SECRET_ACCESS_KEY = '{{ SECRET["aws-key"] }}',
#}
#cmd = [
#    'aws', 's3', 'sync',
#    '{{ mount("syncthing-data") }}',
#    's3://whomst', '--storage-class', 'DEEP_ARCHIVE',
#]
