db_file = '{{ mount("spotti-database") }}/recents.db'
error_file = '{{ var_dir("spotti") }}/status.txt'
bot_pidfile = '{{ var_dir("spotti-downbot") }}/bot-pid.txt'

client_id = '{{ SECRET["spotti-client-id"] }}'
client_secret = '{{ SECRET["spotti-client-secret"] }}'

base_url = 'https://grape.surgery/spotti'
authorize_endpoint = 'authorize'
refresh_endpoint = 'refresh'
get_new_endpoint = ''
show_all_endpoint = 'show-all'
uptime_endpoint = 'up'

get_new_limit = 50

address = '0.0.0.0:44554'
