- name: Deploy gotosocial
  hosts: grape_surgery
  become: true

  roles:
    - server

  vars_files:
    ../configs/vars.yml

  tasks:

    - name: "Ensure gts.dir exists: {{ gts.dir }}"
      ansible.builtin.file:
        path: "{{ gts.dir }}"
        state: directory
        owner: "{{ gts.user }}"
        mode: u=rwx,g=,o=
      notify:
        - Update gotosocial
        - Reload gotosocial
        - Reload systemd

    - name: "Ensure gts.storage exists: {{ gts.storage }}"
      ansible.builtin.file:
        path: "{{ gts.storage }}"
        state: directory
        owner: "{{ gts.user }}"
        mode: u=rwx,g=,o=

    - name: Check version
      ansible.builtin.template:
        src: ../configs/gotosocial_url.txt.j2
        dest: "{{ gts.dir }}/url.txt"
        mode: u=rw,go=r
      notify:
        - Update gotosocial
        - Reload gotosocial

    - name: Template service
      ansible.builtin.template:
        src: ../configs/gotosocial.service.j2
        dest: "{{ systemd_unit_dir }}/gotosocial.service"
      notify:
        - Reload gotosocial
        - Reload systemd

    - name: Template config
      ansible.builtin.template:
        src: ../configs/gotosocial.yaml.j2
        dest: "{{ gts.dir }}/config.yaml"
      notify:
        - Reload gotosocial

  handlers:

    - name: Update gotosocial
      ansible.builtin.shell:
        chdir: "{{ gts.dir }}"
        cmd: |
          wget `cat url.txt`
          tar -xzf `basename $(cat url.txt)`

    - name: Reload gotosocial
      ansible.builtin.service:
        name: gotosocial
        state: restarted
        enabled: true

