# code: language=ansible
- name: Set up htpasswd file
  hosts: grape_surgery
  become: true

  vars_files:
    - ../configs/vars.yml

  tasks:

    - name: "Ensure htpasswd file exists: {{ nginx.htpasswd }}"
      ansible.builtin.file:
        path: "{{ nginx.htpasswd }}"
        state: touch
        owner: "{{ nginx.user }}"
        mode: u=rw,g=,o=

    - name: Back up old htpasswd file
      ansible.builtin.shell: |
        backup="{{ nginx.dir }}/htpasswd_$(date +%s)"
        cp {{ nginx.htpasswd }} "$backup"

    - name: Populate htpasswd file
      ansible.builtin.shell: |
        echo {{ item.value | quote }} | htpasswd -B -C 14 -i {{ nginx.htpasswd }} {{ item.key }}
      loop: "{{ secret.htpasswd | dict2items }}"
