# code: language=ansible
- name: Deploy static pages
  hosts: grape_surgery
  become: true
  become_user: www-data

  roles:
    - server

  vars_files:
    - ../configs/vars.yml

  tasks:
    - name: Remove static files
      ansible.builtin.file:
        state: absent
        path: "{{ nginx.dir }}/www"

    - name: Update static files
      ansible.builtin.copy:
        remote_src: true
        src: "{{ pages.html }}"
        dest: "{{ nginx.dir }}"
        mode: ug=rwx,o=r

    - name: Build blog
      become: true
      become_user: zack
      ansible.builtin.command:
        cmd: zola build
        chdir: "{{ pages.blog }}"
      changed_when: true

    - name: Remove blog
      ansible.builtin.file:
        state: absent
        path: "{{ nginx.dir }}/www/grape.surgery"

    - name: Copy blog
      ansible.builtin.copy:
        remote_src: true
        src: "{{ pages.blog }}"
        dest: "{{ nginx.dir }}/www/grape.surgery"
        mode: ug=rwx,o=r
