# code: language=ansible
- name: Deploy palettizer
  hosts: grape_surgery
  become: true

  roles:
    - server

  vars_files:
    - ../configs/vars.yml

  tasks:

    - name: "Ensure palettizer.dir exists: {{ palettizer.dir }}"
      ansible.builtin.file:
        path: "{{ palettizer.dir }}"
        state: directory
        owner: "{{ palettizer.user }}"
        mode: u=rwx,go=x

    - name: Build palettizer binary
      become: true
      become_user: zack
      ansible.builtin.shell: # noqa: command-instead-of-shell
        chdir: "{{ palettizer.source_dir }}"
        cmd: /snap/bin/cargo build --release
      register: build
      changed_when: "'Compiling' in build.stderr"
      notify:
        - Stop palettizer
        - Copy palettizer
        - Reload palettizer

    - name: Ensure palettizer binary
      ansible.builtin.stat:
        path: "{{ palettizer.dir }}/palettizer"
      register: palettizer_binary
      changed_when: not palettizer_binary.stat.exists
      notify:
        - Stop palettizer
        - Copy palettizer
        - Reload palettizer

    - name: Template palettizer.toml
      ansible.builtin.template:
        src: ../configs/palettizer.toml.j2
        dest: "{{ palettizer.dir }}/config.toml"
        owner: "{{ palettizer.user }}"
        mode: u=r,go=
      notify: Reload palettizer

    - name: Template palettizer.service
      ansible.builtin.template:
        src: ../configs/palettizer.service.j2
        dest: "{{ systemd_unit_dir }}/palettizer.service"
        mode: ugo=r
      notify:
        - Reload systemd
        - Reload palettizer

  handlers:

    - name: Stop palettizer
      ansible.builtin.service:
        name: palettizer
        state: stopped

    - name: Copy palettizer
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item }}"
        dest: "{{ palettizer.dir }}"
        owner: "{{ palettizer.user }}"
        mode: u=rx,go=
      loop:
        # this is terrible
        - "{{ palettizer.source_dir }}/target/release/palettizer"
        - "{{ palettizer.source_dir }}/templates/error.html"
        - "{{ palettizer.source_dir }}/templates/index.html"

    - name: Reload palettizer
      ansible.builtin.service:
        name: palettizer
        state: restarted
        enabled: true

    - name: Reload palettizer_downbot
      ansible.builtin.service:
        name: palettizer_downbot
        state: restarted
        enabled: true
