systemd_unit_dir: /lib/systemd/system
python_interpreter: /server/python-3.12.3/bin/python3

nginx:
  user: www-data
  custom_service: nginx-custom
  dir: /server/nginx
  htpasswd: /server/nginx/htpasswd.new

pages:
  html: /server/source/www
  blog: /server/source/blog/public

syncthing:
  user: syncthing
  dir: /server/syncthing
  data_dir: /mnt/syncthing
  endpoint: /sync/
  ports:
    gui: 8384
    data_public: 22000
    data_private: 22200

spotti:
  user: spotti
  dir: /server/spotti
  database: /server/spotti/recents.db
  source_dir: /server/source/spotti
  database_url: sqlite:///server/spotti/recents.db
  port: 44554
  web_root: /music
  endpoints:
    - name: authorize
      value: authorize
    - name: refresh
      value: refresh
    - name: get_new
      value: ""
    - name: show_all
      value: show-all
    - name: uptime
      value: up

shrub_bot:
  user: shrub_bot
  dir: /server/shrub_bot
  source_dir: /server/source/shrub_bot

dop:
  user: dop
  dir: /server/dop
  source_dir: /server/source/dart-or-penny
  port: 16932
  page_root: /files
  auth_realm: files
