systemd_unit_dir: /lib/systemd/system
python_interpreter: /server/python-3.12.3/bin/python3

nginx:
  user: www-data
  custom_service: nginx-custom
  dir: /server/nginx
  htpasswd: /server/nginx/htpasswd.new

  cert_name: allOfEm
  domains:
    - name: gang-and-friends.com
    - name: oatmeal.gay
    - name: honk.love
    - name: grape.surgery
      include: grape.surgery.conf
    - name: xdd.farm

pages:
  html: /server/source/www
  blog:
    repo: /server/source/blog
    build: /server/source/blog/public
    # TODO better permissions. this might be broken when deploying pages.yml
    dest: /server/nginx/www/grape.surgery

syncthing:
  user: syncthing
  dir: /server/syncthing
  data_dir: /mnt/syncthing
  endpoint: /sync/
  ports:
    gui: 8384
    data_public: 22000
    data_private: 22200
  #binary: /usr/bin/syncthing
  #binary: /server/syncthing/custom/syncthing-linux-amd64-v1.27.12/syncthing
  binary: /server/syncthing/custom/syncthing-linux-amd64-v2.0.10/syncthing

shrub_bot:
  user: shrub_bot
  dir: /server/shrub_bot
  source_dir: /server/source/shrub_bot

dop:
  user: dop
  dir: /server/dop
  source_dir: /server/source/dart-or-penny
  port: 16932
  page_root: /files
  auth_realm: files

palettizer:
  user: palettizer
  dir: /server/palettizer
  source_dir: /server/source/palettizer
  port: 30305
  root: /palettizer
